source 'https://rubygems.org'

gem 'lattice',    github: 'celluloid/lattice'
gem 'webmachine', github: 'seancribbs/webmachine-ruby'
gem 'webmachine-test'
gem 'webmachine-actionview'
gem 'webmachine-sprockets'
gem 'foreman'
gem 'sqlite3'
gem 'sequel'